apiVersion: apps/v1
kind: Deployment
metadata:
  name: alpine-dp
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alpine-dp
  template:
    metadata:
      labels:
        app: alpine-dp
    spec:
      containers:
      - name: alpine
        image: alpine:latest
        command: ["/bin/sh"]
        args: ["-c", "dd if=/dev/zero of=/dev/null bs=1M"]
        resources:
          requests:
            memory: "128Mi"
            cpu: "200m"
          limits:
            memory: "128Mi"
            cpu: "200m"
      restartPolicy: Always
