version: '3'

services:

  mongodb:
    image: mongo:4.4.27
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=prod2
      - MONGO_INITDB_ROOT_PASSWORD=qxT3885JQ6
    volumes:
      - mongo_data_1:/data/db
      - /etc/localtime:/etc/localtime:ro
    restart: always

  rabbitmq:
    image: rabbitmq:3.10.7-management
    container_name: rabbitmq
    hostname: rabbit
    ports:
      - "5672:5672"
      - "15672:15672"
      - "15692:15692"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - rabbitmq_home:/opt/rabbitmq
      - /etc/localtime:/etc/localtime:ro
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
      - RABBITMQ_MNESIA_BASE=/var/lib/rabbitmq/mnesia
    restart: always

volumes:
  mongo_data_1:
  rabbitmq_data:
  rabbitmq_home: