version: "3.7"

services:
  rabbitmq-web-05:
    image: rabbitmq-web-05
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5672:5672
      - 5671:5671
      - 15672:15672
      - 15671:15671
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest