apiVersion: batch/v1
kind: Job
metadata:
  name: job-test
  namespace: default
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      containers:
      - name: pi
        image: busybox:1.36
        command: ["ping", "77.88.8.8"]
      initContainers:
      - name: pre-ping
        image: busybox:1.36
        command: ["ping", "8.8.8.8"]
      restartPolicy: OnFailure
