version: "3.7"

services:
  rabbitmq:
    image: rabbitmq-10-start
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 5672:5672
      - 15672:15672
      - 15692:15692
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - ./rabbitmq_logs:/var/log/rabbitmq
  
  grafana:
    image: grafana/grafana-oss
    ports:
      - 3000:3000
    volumes:
      - ./grafana_dashboards:/dashboards
      - ./grafana-dashboards.yml:/etc/grafana/provisioning/dashboards/rabbitmq.yml
      - ./grafana-datasources.yml:/etc/grafana/provisioning/datasources/prometheus.yml
  
  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml