apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    name: myapp
spec:
  containers:
  - name: mynginx
    image: nginx:stable-alpine3.17
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
