version: '3'

services:

  db:
    image: postgres:14
    restart: always
    container_name: "postgres"
    environment:
      POSTGRES_USER: "sa"
      POSTGRES_PASSWORD: "drx"
      POSTGRES_DB: "drx"
      PG_DATA: "/var/lib/postgresql/data/pgdata"
    ports:
      - 5432:5432
    volumes:
      - /bases/psql:/var/lib/postgresql/data/
      - /bases/backup:/backup
