apiVersion: batch/v1
kind: CronJob
metadata:
  name: cron-test
  namespace: default
spec:
  schedule: "*/10 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          nodeSelector:
            usecase: job-node
          containers:
          - name: hello
            image: busybox:1.36
            command: ["ping", "google.com"]
          restartPolicy: OnFailure
