apiVersion: v1
kind: LimitRange
metadata:
  name: pod-limit
  namespace: default
spec:
  limits:
  - type: Container
    max:
      cpu: "1000m"
      memory: "1Gi"
    defaultRequest:
      cpu: "200m"
      memory: "128Mi"