apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-dp
spec:
  selector:
    matchLabels:
      app: httpd-dp  # Метка должна совпадать с той, что указана в selector сервиса
  template:
    metadata:
      labels:
        app: httpd-dp  # Метка должна совпадать с selector сервиса
    spec:
      containers:
      - name: httpd-dp
        image: httpd
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80

