apiVersion: v1
kind: Service
metadata:
  name: http-svc-nodeport
spec:
  type: NodePort
  selector:
    app: httpd-dp
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: http
      nodePort: 32501
    - protocol: TCP
      name: https
      port: 443
      targetPort: https
      nodePort: 32501
