---
# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep-main
  labels:
    app: dep-main
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dep-main
  template:
    metadata:
      labels:
        app: dep-main
    spec:
      containers:
      - name: production
        image: registry.k8s.io/ingress-nginx/e2e-test-echo@sha256:6fc5aa2994c86575975bb20a5203651207029a0d28e3f491d8a127d08baadab4
        ports:
        - containerPort: 80
        - containerPort: 443
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
---
# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep-canary
  labels:
    app: dep-canary
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dep-canary
  template:
    metadata:
      labels:
        app: dep-canary
    spec:
      containers:
      - name: canary
        image: registry.k8s.io/ingress-nginx/e2e-test-echo@sha256:6fc5aa2994c86575975bb20a5203651207029a0d28e3f491d8a127d08baadab4
        ports:
        - containerPort: 80
        - containerPort: 443
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
---
# Service
apiVersion: v1
kind: Service
metadata:
  name: svc-dep-main
  labels:
    app: dep-main
spec:
  ports:
  - port: 8080
    targetPort: 80
    protocol: TCP
    name: http
  - port: 8443
    targetPort: 443
    protocol: TCP
    name: https
  selector:
    app: dep-main
---
# Service
apiVersion: v1
kind: Service
metadata:
  name: svc-dep-canary
  labels:
    app: dep-canary
spec:
  ports:
  - port: 9090
    targetPort: 80
    protocol: TCP
    name: http
  - port: 9443
    targetPort: 443
    protocol: TCP
    name: https
  selector:
    app: dep-canary

---

# получаем ip ingress
# kubectl get svc -n ingress-nginx

