apiVersion: v1
kind: Service
metadata:
  name: http-svc-int
spec:
  type: ClusterIP
  selector:
    app: httpd-dp
  ports:
  - protocol: TCP
    name: http
    port: 80
    targetPort: http
  - protocol: TCP
    name: https
    port: 443
    targetPort: https
