version: "3"
services:
  fluentd:
    build: ./fluentd
    environment:
      - FLUENTD_CONF=fluentd.conf
    depends_on:
      - elasticsearch
    volumes:
      - ./fluentd:/fluentd/etc
    links:
      - "elasticsearch"
    ports:
      - "24224:24224"
      - "24224:24224/udp"


  elasticsearch:
    image: elasticsearch:7.13.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
    expose:
      - 9200
    ports:
      - "9200:9200"
      - "9300:9300"

  kibana:
    image: kibana:7.13.1
    environment:
      NODE_OPTIONS: '--max-old-space-size=512'
    depends_on:
      - elasticsearch
      - fluentd
    links:
      - "elasticsearch"
    ports:
      - "5601:5601"
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224