apiVersion: v1
kind: Pod
metadata:
  name: kubia-manual-gpu
  labels:
    creation_method: manual
    env: prod
spec:
  nodeSelector: 
    gpu: "true"
  containers:
  - name: kubia
    image: dmitriypalchikov1/kubia
    ports:
    - containerPort: 8080
      protocol: TCP