apiVersion: v1
kind: Pod
metadata:
  name: kubia-manual
spec:
  containers:
  - name: kubia
    image          : dmitriypalchikov1/kubia
    ports:
    - containerPort: 8080
      protocol     : TCP

