apiVersion: apps/v1
kind: Deployment
metadata:
  name: autoscale-dp
  labels:
    app: autoscale-dp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: autoscale-dp
  template:
    metadata:
      labels:
        app: autoscale-dp
    spec:
      containers:
      - image: luxas/autoscale-demo:v0.1.2
        name: metrics-provider
        resources:
          requests:
            cpu: "100m"
            memory: "200Mi"
          limits:
            cpu: "500m"
            memory: "400Mi"
        ports:
        - name: http
          containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: autoscale-dp
  name: autoscale-dp
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: autoscale-dp
  type: ClusterIP