apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: autoscale-monitor
  namespace: default
  labels:
    release: prometheus-stack
spec:
  selector:
    matchLabels:
      app: autoscale-dp
  podMetricsEndpoints:
    - port: http
      path: /metrics